"""initial schema

Revision ID: 2fb2985193f2
Revises: 
Create Date: 2026-09-22 09:52:40.324639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb2985193f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_alerts_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)
        batch_op.create_index('ix_alerts_status_severity', ['status', 'severity'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('customer_type', sa.String(length=20), nullable=False),
    sa.Column('industry', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_customer_code'), ['customer_code'], unique=True)
        batch_op.create_index('ix_customers_type', ['customer_type'], unique=False)

    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=80), nullable=False),
    sa.Column('destination', sa.String(length=80), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('expected_duration_hours', sa.Float(), nullable=False),
    sa.Column('route_type', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin', 'destination', name='uq_route_origin_dest')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=20), nullable=False),
    sa.Column('registration_number', sa.String(length=30), nullable=False),
    sa.Column('vehicle_type', sa.String(length=30), nullable=False),
    sa.Column('transporter', sa.String(length=100), nullable=False),
    sa.Column('capacity_kg', sa.Float(), nullable=True),
    sa.Column('fuel_type', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_transporter'), ['transporter'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_vehicle_id'), ['vehicle_id'], unique=True)

    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('capacity_units', sa.Float(), nullable=False),
    sa.Column('occupied_units', sa.Float(), nullable=False),
    sa.Column('warehouse_type', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouses_warehouse_code'), ['warehouse_code'], unique=True)

    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=80), nullable=False),
    sa.Column('destination', sa.String(length=80), nullable=False),
    sa.Column('country_of_origin', sa.String(length=80), nullable=True),
    sa.Column('country_of_destination', sa.String(length=80), nullable=True),
    sa.Column('cargo_type', sa.String(length=40), nullable=False),
    sa.Column('container_type', sa.String(length=40), nullable=True),
    sa.Column('declared_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('volume_m3', sa.Float(), nullable=True),
    sa.Column('planned_departure', sa.DateTime(), nullable=False),
    sa.Column('actual_departure', sa.DateTime(), nullable=True),
    sa.Column('planned_arrival', sa.DateTime(), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('delay_hours', sa.Float(), nullable=True),
    sa.Column('transit_hours', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('delay_cause', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipments_actual_arrival'), ['actual_arrival'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_cargo_type'), ['cargo_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index('ix_shipments_customer_status', ['customer_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_destination'), ['destination'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_origin'), ['origin'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_planned_arrival'), ['planned_arrival'], unique=False)
        batch_op.create_index('ix_shipments_planned_dep', ['planned_departure'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_planned_departure'), ['planned_departure'], unique=False)
        batch_op.create_index('ix_shipments_route', ['origin', 'destination'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_shipment_id'), ['shipment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_shipments_status'), ['status'], unique=False)

    op.create_table('customs_declarations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('declaration_id', sa.String(length=20), nullable=False),
    sa.Column('shipment_id', sa.String(length=20), nullable=False),
    sa.Column('declaration_date', sa.DateTime(), nullable=False),
    sa.Column('clearance_date', sa.DateTime(), nullable=True),
    sa.Column('customs_status', sa.String(length=20), nullable=False),
    sa.Column('declared_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('duties_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('clearance_duration_hours', sa.Float(), nullable=True),
    sa.Column('sla_hours', sa.Float(), nullable=False),
    sa.Column('sla_status', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customs_declarations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customs_declarations_declaration_date'), ['declaration_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_customs_declarations_declaration_id'), ['declaration_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_customs_declarations_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index('ix_customs_status_date', ['customs_status', 'declaration_date'], unique=False)

    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.String(length=20), nullable=False),
    sa.Column('shipment_id', sa.String(length=20), nullable=False),
    sa.Column('vehicle_id', sa.String(length=20), nullable=False),
    sa.Column('driver_name', sa.String(length=120), nullable=True),
    sa.Column('origin', sa.String(length=80), nullable=False),
    sa.Column('destination', sa.String(length=80), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('planned_arrival', sa.DateTime(), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(), nullable=True),
    sa.Column('planned_duration_hours', sa.Float(), nullable=False),
    sa.Column('actual_duration_hours', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('fuel_liters', sa.Float(), nullable=True),
    sa.Column('trip_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trips_departure_time'), ['departure_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_trip_id'), ['trip_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_trips_trip_status'), ['trip_status'], unique=False)
        batch_op.create_index('ix_trips_vehicle_dep', ['vehicle_id', 'departure_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('warehouse_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.String(length=20), nullable=False),
    sa.Column('transaction_type', sa.String(length=15), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('storage_duration_days', sa.Float(), nullable=True),
    sa.Column('storage_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('warehouse_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouse_transactions_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_transactions_transaction_date'), ['transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_transactions_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_index('ix_wtrans_type_date', ['transaction_type', 'transaction_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_wtrans_type_date')
        batch_op.drop_index(batch_op.f('ix_warehouse_transactions_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_warehouse_transactions_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_warehouse_transactions_shipment_id'))

    op.drop_table('warehouse_transactions')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trips_vehicle_id'))
        batch_op.drop_index('ix_trips_vehicle_dep')
        batch_op.drop_index(batch_op.f('ix_trips_trip_status'))
        batch_op.drop_index(batch_op.f('ix_trips_trip_id'))
        batch_op.drop_index(batch_op.f('ix_trips_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_trips_departure_time'))

    op.drop_table('trips')
    with op.batch_alter_table('customs_declarations', schema=None) as batch_op:
        batch_op.drop_index('ix_customs_status_date')
        batch_op.drop_index(batch_op.f('ix_customs_declarations_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_customs_declarations_declaration_id'))
        batch_op.drop_index(batch_op.f('ix_customs_declarations_declaration_date'))

    op.drop_table('customs_declarations')
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipments_status'))
        batch_op.drop_index(batch_op.f('ix_shipments_shipment_id'))
        batch_op.drop_index('ix_shipments_route')
        batch_op.drop_index(batch_op.f('ix_shipments_planned_departure'))
        batch_op.drop_index('ix_shipments_planned_dep')
        batch_op.drop_index(batch_op.f('ix_shipments_planned_arrival'))
        batch_op.drop_index(batch_op.f('ix_shipments_origin'))
        batch_op.drop_index(batch_op.f('ix_shipments_destination'))
        batch_op.drop_index('ix_shipments_customer_status')
        batch_op.drop_index(batch_op.f('ix_shipments_customer_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_cargo_type'))
        batch_op.drop_index(batch_op.f('ix_shipments_actual_arrival'))

    op.drop_table('shipments')
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouses_warehouse_code'))

    op.drop_table('warehouses')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_vehicles_transporter'))

    op.drop_table('vehicles')
    op.drop_table('routes')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('ix_customers_type')
        batch_op.drop_index(batch_op.f('ix_customers_customer_code'))

    op.drop_table('customers')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_alerts_status_severity')
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index('ix_alerts_entity')
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_alert_type'))

    op.drop_table('alerts')
    # ### end Alembic commands ###
